version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - .:/Tabular/opt/app/
    environment:
      FLASK_APP: src.app.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
    command: ["flask", "run", "--host=0.0.0.0", "--port=8010"]
